# Generated by Django 2.1.5 on 2021-07-21 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GRsystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='Department',
            field=models.CharField(choices=[('CSIS', 'CSIS'), ('Academic', 'Academic'), ('Student Affairs', 'Student Affairs'), ('Finance', 'Finance'), ('Other', 'Other')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='type_user',
            field=models.CharField(choices=[('student', 'student'), ('staff', 'staff'), ('admin', 'admin')], default='student', max_length=20),
        ),
    ]
