# Generated by Django 2.1.5 on 2021-07-21 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GRsystem', '0002_auto_20210721_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Department',
            field=models.CharField(choices=[('CSIS', 'CSIS'), ('Academic', 'Academic'), ('Student Affairs', 'Student Affairs'), ('Finance', 'Finance'), ('Other', 'Other')], max_length=200, null=True),
        ),
    ]
