# Generated by Django 2.1.5 on 2021-07-21 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GRsystem', '0003_profile_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='college',
            field=models.CharField(blank=True, choices=[('CoE', 'COE'), ('CDS', 'CDS'), ('CST', 'CST')], max_length=29),
        ),
    ]
